blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('post/<int:post_id>/', views.post, name='post'),
    path('new_post/', views.new_post, name='new_post'),
    path('new_comment/<int:post_id>/', views.new_comment, name='new_comment'),
    path('about_us/', views.about_us, name='about_us')
]

helping_hand/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls'))
]

blog/models.py
from django.db import models
from django.utils import timezone


class Post(models.Model):
    title = models.CharField(max_length=250)
    body = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    body = models.CharField(max_length=250)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.body[:50]}"

blog/forms.py
from .models import Post, Comment
from django import forms


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'body')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)

blog/views.py
from django.shortcuts import render, redirect
from .models import Post
from django.views.generic import ListView
from .forms import PostForm, CommentForm


class IndexView(ListView):
    queryset = Post.objects.order_by('-date_added')
    context_object_name = 'posts'
    paginate_by = 10
    template_name = 'blog/index.html'


def post(request, post_id):
    post = Post.objects.get(id=post_id)
    comments = post.comment_set.order_by('-date_added')
    context = {'post': post, 'comments': comments}
    return render(request, 'blog/post.html', context)


def new_post(request):
    if request.method != 'POST':
        form = PostForm()
    else:
        form = PostForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('blog:index')
    context = {'form': form}
    return render(request, 'blog/new_post.html', context)


def new_comment(request, post_id):
    post = Post.objects.get(id=post_id)
    if request.method != 'POST':
        form = CommentForm()
    else:
        form = CommentForm(data=request.POST)
        new_comment = form.save(commit=False)
        new_comment.post = post
        new_comment.save()
        return redirect('blog:post', post_id=post_id)
    context = {'form': form, 'post': post}
    return render(request, 'blog/new_comment.html', context)


def about_us(request):
    return render(request, 'blog/about_us.html')

blog/templates/blog/about_us.html
{% extends 'blog/base.html' %}
{% load static %}
{% block title %}About Us{% endblock title %}
{% block content %}

    <main class="container">
        <div class="row g-5">

            <div class="col-md-8">
                 <h3 class="pb-4 mb-4 fst-italic border-bottom" style="color: coral">
                    ABOUT US
                 </h3>
                <article class="blog-post">
                    <h2 class="blog-post-title">WHO ARE WE?</h2>
                    <p class="blog-post-meta">{{ post.date_added }}</p>

                    <p>Helping Hand is a simple platform by The Good Writer in partnership with Coding With Che aimed
                    at empowering local citizens of Zimbabwe to share some of the intricate stories of their day to day lives.</p>
                    <hr>
                    <h2 class="blog-post-title">WHY SHARE?</h2>
                    <p class="blog-post-meta">{{ post.date_added }}</p>

                    <p>Mental health being one of the pressing issues in today's society, we want people to be able to find help on our
                    platform mainly in the form of advice from the comments.  We want people to open up and show other users that they are not alone
                    in whatever they are fighting, and of course we want them to be better at the end of the day.</p>
                    <hr>
                    <h2 class="blog-post-title">WHY US?</h2>
                    <p class="blog-post-meta">{{ post.date_added }}</p>

                    <p>With the increase of ghost accounts on the popular social sites, it came to my realization that at times people
                    don't want to be known on social media, their personal details, their browsing data (which is definitely being monitored by the big
                        social companies)
                        .  Thats why we made this service such that the users are not known (we do not allow for creation of accounts)
                    ensuring that users will maximize their sharing since there is no fear of judgement.</p>
                    <hr>
                     <h2 class="blog-post-title">CONTACT DETAILS</h2>
                    <p class="blog-post-meta">{{ post.date_added }}</p>
                    <p>Email: mukanhairic@gmail.com</p>
                    <p>Whatsapp: <a
           href="https://wa.me/263778754931" target='_blank'> <i class= "fa fa-whatsapp"></i>263778754931</a></p>
                    <hr>


                </article>

            </div>

             <div class="col-md-4">
                  <div class="position-sticky" style="top: 2rem;">
                    <div class="p-4 mb-3 bg-light rounded">
                      <h4 class="fst-italic">Helping Hand <img src="{% static 'media/knowledge.png' %}" width="40"></h4>
                      <p class="mb-0">You've got a pressing issue and want help but don't want people judging you?  Our platform makes sure you are anonymous and give you the ability to share anything without people knowing you.</p>
                    </div>
                       <div class="col">
                            <div class="card card-cover h-100 overflow-hidden text-white bg-dark rounded-5 shadow-lg" style="background-image: url('/static/css/images/unsplash-photo-2.jpg');">
                              <div class="d-flex flex-column h-100 p-5 pb-3 text-white text-shadow-1">
                                <h2 class="pt-5 mt-5 mb-4 display-6 lh-1 fw-bold">Good things always come to those who wait</h2>
                                <ul class="d-flex list-unstyled mt-auto">
                                  <li class="me-auto">
                                    <img src="{% static 'media/Che.jpg' %}" alt="Che" width="32" height="32" class="rounded-circle border border-white">
                                  </li>
                                  <li class="d-flex align-items-center me-3">
                                    <svg class="bi me-2" width="1em" height="1em"> </svg>
                                    <small>Kwekwe</small>
                                  </li>
                                  <li class="d-flex align-items-center">
                                    <svg class="bi me-2" width="1em" height="1em"></svg>
                                    <small>The Good Writer</small>
                                  </li>
                                </ul>
                              </div>
                            </div>
                        </div>
                    </div>

                  </div>
             </div>
        <br>
     <p class="fs-5 text-muted">&copy;  2022 - The Good Writer | Helping Hand</p>

    </main>

{% endblock content %}

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width-device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" type="text/css" href="{% static '/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static '/css/blog.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static '/css/navbar.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static '/css/features.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static '/css/mydesign.css' %}">

    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>


</head>
<body>


<main>
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark" aria-label="Third navbar example">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'blog:index' %}" style="font-size: 40px; font-family: 'Eras Bold ITC'">Helping Hand</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample03" aria-controls="navbarsExample03" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExample03">
        <ul class="navbar-nav me-auto mb-2 mb-sm-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'blog:index' %}">Home</a>
          </li>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="dropdown03" data-bs-toggle="dropdown" aria-expanded="false">Quick Links</a>
            <ul class="dropdown-menu" aria-labelledby="dropdown03">
              <li><a class="dropdown-item" href="{% url 'blog:new_post' %}">Add new post</a></li>
              <li><a class="dropdown-item" href="{% url 'blog:about_us' %}">About Us</a></li>
            </ul>
          </li>
        </ul>
        <form>
          <input class="form-control" type="text" placeholder="Search" aria-label="Search">
        </form>
      </div>
    </div>
  </nav>

</main>


{% block content %}
{% endblock content %}


</body>
</html>

blog/templates/blog/index.html
{% extends 'blog/base.html' %}
{% load static %}
{% block title %}Home{% endblock title %}
{% block content %}

    <main class="container">
        <div class="row g-5">

            <div class="col-md-8">
                 <h3 class="pb-4 mb-4 fst-italic border-bottom" style="color: coral">
                    POSTS
                 </h3>
                {% for post in posts %}
                <article class="blog-post">
                    <p><h2 class="blog-post-title"><a href="{% url 'blog:post' post.id %}" style="color: #83a1ca;">{{ post.title }}</a></h2></p>
                    <p class="blog-post-meta">{{ post.date_added }}</p>

                    <p>{{ post.body }}</p>
                    <hr>

                </article>
                {% empty %}
                    <li>No posts have been added yet.</li>
                {% endfor %}
                {% include "blog/pagination.html" with page=page_obj %}
            </div>

             <div class="col-md-4">
                  <div class="position-sticky" style="top: 2rem;">
                    <div class="p-4 mb-3 bg-light rounded">
                      <h4 class="fst-italic">Helping Hand <img src="{% static 'media/knowledge.png' %}" width="40"></h4>
                      <p class="mb-0">You've got a pressing issue and want help but don't want people judging you?  Our platform makes sure you are anonymous and give you the ability to share anything without people knowing you.</p>
                    </div>
                       <div class="col">
                            <div class="card card-cover h-100 overflow-hidden text-white bg-dark rounded-5 shadow-lg" style="background-image: url('/static/css/images/unsplash-photo-2.jpg');">
                              <div class="d-flex flex-column h-100 p-5 pb-3 text-white text-shadow-1">
                                <h2 class="pt-5 mt-5 mb-4 display-6 lh-1 fw-bold">Good things always come to those who wait</h2>
                                <ul class="d-flex list-unstyled mt-auto">
                                  <li class="me-auto">
                                    <img src="{% static 'media/Che.jpg' %}" alt="Che" width="32" height="32" class="rounded-circle border border-white">
                                  </li>
                                  <li class="d-flex align-items-center me-3">
                                    <svg class="bi me-2" width="1em" height="1em"> </svg>
                                    <small>Kwekwe</small>
                                  </li>
                                  <li class="d-flex align-items-center">
                                    <svg class="bi me-2" width="1em" height="1em"></svg>
                                    <small>The Good Writer</small>
                                  </li>
                                </ul>
                              </div>
                            </div>
                        </div>
                    </div>

                  </div>
             </div>

    </main>

{% endblock content %}

blog/templates/blog/new_comment.html
{% extends 'blog/base.html' %}
{% load static %}
{% block title %}New Comment{% endblock title %}
{% block content %}
   <main class="container">
            <div class="row g-5">
                <div class="col-md-8" >
                    <form class="my-form" method="post" action="{% url 'blog:new_comment' post.id %}">
                        {% csrf_token %}
                        <div class="form-group">
                            <label>Comment: </label>
                            <textarea type="text" name="body"></textarea>
                        </div>
                        <input class="button" type="submit" value="Post">
                    </form>
                </div>
                <div class="col-md-4">
                  <div class="position-sticky" style="top: 2rem;">
                    <div class="p-4 mb-3 bg-light rounded">
                      <h4 class="fst-italic">Helping Hand <img src="{% static 'media/knowledge.png' %}" width="40"></h4>
                      <p class="mb-0">You've got a pressing issue and want help but don't want people judging you?  Our platform makes sure you are anonymous and give you the ability to share anything without people knowing you.</p>
                    </div>
                       <div class="col">
                            <div class="card card-cover h-100 overflow-hidden text-white bg-dark rounded-5 shadow-lg" style="background-image: url('/static/css/images/unsplash-photo-2.jpg');">
                              <div class="d-flex flex-column h-100 p-5 pb-3 text-white text-shadow-1">
                                <h2 class="pt-5 mt-5 mb-4 display-6 lh-1 fw-bold">Good things always come to those who wait</h2>
                                <ul class="d-flex list-unstyled mt-auto">
                                  <li class="me-auto">
                                    <img src="{% static 'media/Che.jpg' %}" alt="Che" width="32" height="32" class="rounded-circle border border-white">
                                  </li>
                                  <li class="d-flex align-items-center me-3">
                                    <svg class="bi me-2" width="1em" height="1em"> </svg>
                                    <small>Kwekwe</small>
                                  </li>
                                  <li class="d-flex align-items-center">
                                    <svg class="bi me-2" width="1em" height="1em"></svg>
                                    <small>The Good Writer</small>
                                  </li>
                                </ul>
                              </div>
                            </div>
                        </div>
                    </div>
                </div>



            </div>
        </main>
{% endblock content %}

blog/templates/blog/new_post.html
{% extends 'blog/base.html' %}
{% load static %}
{% block title %}Add a new post{% endblock title %}
{% block content %}
        <main class="container">
            <div class="row g-5">
                <div class="col-md-8" >
                    <form class="my-form" method="post" action="{% url 'blog:new_post' %}">
                        {% csrf_token %}
                        <div class="form-group">
                            <label>Title: </label>
                            <input type="text" name="title">
                        </div>
                        <div class="form-group">
                            <label>Text: </label>
                            <textarea type="text" name="body"></textarea>
                        </div>
                        <div class="form-group">
                             <p>
                                {% if field.help_text %}
                                    {{ field.help_text }}
                                {% endif %}
                            </p>
                        </div>
                        <div class="form-group">
                            {% for error in field.errors %}
                                <h8>{{ error }}</h8>
                            {% endfor %}
                        </div>

                        <input class="button" type="submit" value="Post">
                    </form>
                </div>
                <div class="col-md-4">
                  <div class="position-sticky" style="top: 2rem;">
                    <div class="p-4 mb-3 bg-light rounded">
                      <h4 class="fst-italic">Helping Hand <img src="{% static 'media/knowledge.png' %}" width="40"></h4>
                      <p class="mb-0">You've got a pressing issue and want help but don't want people judging you?  Our platform makes sure you are anonymous and give you the ability to share anything without people knowing you.</p>
                    </div>
                       <div class="col">
                            <div class="card card-cover h-100 overflow-hidden text-white bg-dark rounded-5 shadow-lg" style="background-image: url('/static/css/images/unsplash-photo-2.jpg');">
                              <div class="d-flex flex-column h-100 p-5 pb-3 text-white text-shadow-1">
                                <h2 class="pt-5 mt-5 mb-4 display-6 lh-1 fw-bold">Good things always come to those who wait</h2>
                                <ul class="d-flex list-unstyled mt-auto">
                                  <li class="me-auto">
                                    <img src="{% static 'media/Che.jpg' %}" alt="Che" width="32" height="32" class="rounded-circle border border-white">
                                  </li>
                                  <li class="d-flex align-items-center me-3">
                                    <svg class="bi me-2" width="1em" height="1em"> </svg>
                                    <small>Kwekwe</small>
                                  </li>
                                  <li class="d-flex align-items-center">
                                    <svg class="bi me-2" width="1em" height="1em"></svg>
                                    <small>The Good Writer</small>
                                  </li>
                                </ul>
                              </div>
                            </div>
                        </div>
                    </div>
                </div>



            </div>
        </main>
{% endblock content %}

blog/templates/blog/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
            <a style="color: coral" href="?page={{ page.previous_page_number }}">Previous</a>
        {% endif %}
        <span class="current">
            Page {{ page.number }} of {{ page.paginator.num_pages }}.
        </span>
        {% if page.has_next %}
            <a style="color: coral" href="?page={{ page.next_page_number }}">Next</a>
        {% endif %}
    </span>
</div>

blog/templates/blog/post.html
{% extends 'blog/base.html' %}
{% load static %}
{% block title %}Post{% endblock title %}
{% block content %}

   <main class="container">
        <div class="row g-5">

            <div class="col-md-8">
                 <h3 class="pb-4 mb-4 fst-italic border-bottom" style="color: coral">
                    POST
                 </h3>
                <article class="blog-post">
                    <h2 class="blog-post-title">{{ post.title }}</h2>
                    <p class="blog-post-meta">{{ post.date_added }}</p>

                    <p>{{ post.body }}</p>
                    <hr>
                    {% with comments.count as total_comments %}
                        <h3>{{ total_comments }} comment{{ total_comments|pluralize }}</h3>
                        <a style="color: coral" href="{% url 'blog:new_comment' post.id %}">Add comment</a>
                    {% endwith %}
                    <ul>
                        {% for comment in comments %}
                            <p>{{ comment.body }}</p>
                            <ul><li><small>{{ comment.date_added }}</small></li></ul>
                            <hr>
                            {% empty %}
                            <li>No comments have been added yet.</li>
                        {% endfor %}
                    </ul>

                </article>

            </div>
             <div class="col-md-4">
                  <div class="position-sticky" style="top: 2rem;">
                    <div class="p-4 mb-3 bg-light rounded">
                      <h4 class="fst-italic">Helping Hand <img src="{% static 'media/knowledge.png' %}" width="40"></h4>
                      <p class="mb-0">You've got a pressing issue and want help but don't want people judging you?  Our platform makes sure you are anonymous and give you the ability to share anything without people knowing you.</p>
                    </div>
                       <div class="col">
                            <div class="card card-cover h-100 overflow-hidden text-white bg-dark rounded-5 shadow-lg" style="background-image: url('/static/css/images/unsplash-photo-2.jpg');">
                              <div class="d-flex flex-column h-100 p-5 pb-3 text-white text-shadow-1">
                                <h2 class="pt-5 mt-5 mb-4 display-6 lh-1 fw-bold">Good things always come to those who wait</h2>
                                <ul class="d-flex list-unstyled mt-auto">
                                  <li class="me-auto">
                                    <img src="{% static 'media/Che.jpg' %}" alt="Che" width="32" height="32" class="rounded-circle border border-white">
                                  </li>
                                  <li class="d-flex align-items-center me-3">
                                    <svg class="bi me-2" width="1em" height="1em"> </svg>
                                    <small>Kwekwe</small>
                                  </li>
                                  <li class="d-flex align-items-center">
                                    <svg class="bi me-2" width="1em" height="1em"></svg>
                                    <small>The Good Writer</small>
                                  </li>
                                </ul>
                              </div>
                            </div>
                        </div>
                    </div>

                  </div>
             </div>
    </main>>


{% endblock content %}